### ISSUE TITLE
phpstan-param Class::CONST_* throws exceptions

### ISSUE THREAD

**Issue by frankdekker** [123inkt/accessorpair-constraint#39]
```
class Example
{
    public const TYPE_A = 'a';
    public const TYPE_B = 'b';

    /**
     * @phpstan-param Example::TYPE_* $type
     */
    public function __construct(private string $type)
    {
    }

    public function getType(): string {
        return $this->type;
    }
}
```

Throws error message:
`Unable to run constraint on class. "\Example::TYPE_*" is not a valid Fqsen.`

**Comment by bram123** [comment]
Yes that syntax is not supported at the moment.
Using https://github.com/phpDocumentor/TypeResolver to check the phpdoc, and that package doesn't have too much support for the phpstan/psalm syntax.
